#!/bin/sh
# Kaolin - Exfoliate your face
# Copyright (c) 2008 Devin Torres
# Licensed under the MIT license.

NOHUP=`which nohup`

if [ -z "$NOHUP" ]
then
  echo "'nohup' not found.  Bailing...";
  exit 1;
fi

if [ ! -r ./bin/mud ]
then
  echo "'./bin/mud' not found.  Bailing...";
  exit 1;
fi

if [ ! -r /dev/null ]
then
  echo "'/dev/null' not found.  Bailing...";
  exit 1;
fi

nohup ./bin/mud >> /dev/null &
